apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  selector:
    app: {{ template "name" . }}
  ports:
    - port: {{ .Values.externalPort }}
      name: http-jira-ticket-checker
      targetPort: {{ .Values.internalPort }}
