version: 2.1

executors:
  cd:
    docker:
      - image: node:10.16.3-buster

jobs:
  lint_test:
    executor: cd
    steps:
      - checkout
      - run:
          name: Lint repository
          command: echo TODO
      - run:
          name: Test repository
          command: echo TODO
  deploy:
    executor: cd
    steps:
      - checkout
      - run:
          name: Synchronize deployment with Github repository
          command: |
            npx sync-glitch-cli
  
workflows:
  version: 2
  workflow:
    jobs:
      - lint_test
      - deploy:
          filters:
            branches:
              only:
                - master
