version: 2.1

executors:
  cd:
    docker:
      - image: circleci/node:10.16

jobs:
  deploy:
    executor: cd
    steps:
      - checkout
      - run:
          name: Synchronize deployment with Github repository
          command: |
            npx sync-glitch-cli
  
workflows:
  version: 2
  workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
          context: org-global-v2